classDiagram
    class Student {
        - _name: str
        - _courses: list<Course>
        + enroll(course: Course)
    }

    class Course {
        - _title: str
        - _students: list<Student>
        + add_student(student: Student)
    }

    Student "1..*" -- "1..*" Course : enrolls in
    %% Course "1" --* "0..*" Student : has students
